// Login types
export const LOGINREQUEST = 'LOGIN_REQUEST';
export const LOGINSUCCESS = 'LOGIN_SUCCESS';
export const LOGINFAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CHECKAUTH = 'CHECK_AUTH';


export const CREATE_ORDERMISSION_REQUEST = 'CREATE_ORDERMISSION_REQUEST';
export const CREATE_ORDERMISSION_SUCCESS = 'CREATE_ORDERMISSION_SUCCESS';
export const CREATE_ORDERMISSION_FAILURE = 'CREATE_ORDERMISSION_FAILURE';
export const UPDATE_ORDERMISSION_REQUEST = 'UPDATE_ORDERMISSION_REQUEST';
export const UPDATE_ORDERMISSION_SUCCESS = 'UPDATE_ORDERMISSION_SUCCESS';
export const UPDATE_ORDERMISSION_FAILURE = 'UPDATE_ORDERMISSION_FAILURE';
export const DELETE_ORDERMISSION_REQUEST = 'DELETE_ORDERMISSION_REQUEST';
export const DELETE_ORDERMISSION_SUCCESS = 'DELETE_ORDERMISSION_SUCCESS';
export const DELETE_ORDERMISSION_FAILURE = 'DELETE_ORDERMISSION_FAILURE';
export const FETCH_ORDERMISSIONS_REQUEST = "FETCH_ORDERMISSIONS_REQUEST";
export const FETCH_ORDERMISSIONS_SUCCESS = "FETCH_ORDERMISSIONS_SUCCESS";
export const FETCH_ORDERMISSIONS_FAILURE = "FETCH_ORDERMISSIONS_FAILURE";
export const UPDATESTATUS_ORDERMISSION_REQUEST = "UPDATESTATUS_ORDERMISSION_REQUEST";
export const UPDATESTATUS_ORDERMISSION_SUCCESS = "UPDATESTATUS_ORDERMISSION_SUCCESS";
export const UPDATESTATUS_ORDERMISSION_FAILURE = "UPDATESTATUS_ORDERMISSION_FAILURE";



export const FETCH_ENTERPRISES_REQUEST = 'FETCH_ENTERPRISES_REQUEST';
export const FETCH_ENTERPRISES_SUCCESS = 'FETCH_ENTERPRISES_SUCCESS';
export const FETCH_ENTERPRISES_FAILURE = 'FETCH_ENTERPRISES_FAILURE';
export const ADD_ENTERPRISE_REQUEST = 'ADD_ENTERPRISE_REQUEST';
export const ADD_ENTERPRISE_SUCCESS = 'ADD_ENTERPRISE_SUCCESS';
export const ADD_ENTERPRISE_FAILURE = 'ADD_ENTERPRISE_FAILURE';
export const UPDATE_ENTERPRISE_REQUEST = 'UPDATE_ENTERPRISE_REQUEST';
export const UPDATE_ENTERPRISE_SUCCESS = 'UPDATE_ENTERPRISE_SUCCESS';
export const UPDATE_ENTERPRISE_FAILURE = 'UPDATE_ENTERPRISE_FAILURE';

export const CREATE_CONTROL_REQUEST = 'CREATE_CONTROL_REQUEST';
export const CREATE_CONTROL_SUCCESS = 'CREATE_CONTROL_SUCCESS';
export const CREATE_CONTROL_FAILURE = 'CREATE_CONTROL_FAILURE';
export const UPDATE_CONTROL_REQUEST = 'UPDATE_CONTROL_REQUEST';
export const UPDATE_CONTROL_SUCCESS = 'UPDATE_CONTROL_SUCCESS';
export const UPDATE_CONTROL_FAILURE = 'UPDATE_CONTROL_FAILURE';
export const DELETE_CONTROL_REQUEST = 'DELETE_CONTROL_REQUEST';
export const DELETE_CONTROL_SUCCESS = 'DELETE_CONTROL_SUCCESS';
export const DELETE_CONTROL_FAILURE = 'DELETE_CONTROL_FAILURE';
export const FETCH_CONTROLS_REQUEST = "FETCH_CONTROLS_REQUEST";
export const FETCH_CONTROLS_SUCCESS = "FETCH_CONTROLS_SUCCESS";
export const FETCH_CONTROLS_FAILURE = "FETCH_CONTROLS_FAILURE";